import {
  type RouteConfig,
  index,
  layout,
  route,
} from "@react-router/dev/routes";

export default [
  route("auth/session/login", "routes/auth.session.login.tsx"),
  route("auth/session/refresh", "routes/auth.session.refresh.tsx"),
  route("auth/session/logout", "routes/auth.session.logout.tsx"),
  route("auth/session/me", "routes/auth.session.me.tsx"),
  route("auth/session/register", "routes/auth.session.register.tsx"),
  route("auth/session/gateway/*", "routes/auth.session.gateway.tsx"),
  route("auth/api/*", "routes/gateway.auth-api.tsx"),
  route("product/*", "routes/gateway.product.tsx"),
  route("product-images/*", "routes/gateway.product-images.tsx"),
  route("inventory/*", "routes/gateway.inventory.tsx"),
  route("order/*", "routes/gateway.order.tsx"),
  route("notification/*", "routes/gateway.notification.tsx"),
  route("login", "routes/login.tsx"),
  layout("routes/admin.tsx", [
    index("routes/dashboard.tsx"),
    route("products", "routes/products.tsx"),
    route("products/new", "routes/products.new.tsx"),
    route("products/:id/SKU/:skuId", "routes/products.$id.SKU.$skuId.tsx"),
    route("products/:id", "routes/products.$id.tsx"),
    route("catalog", "routes/catalog.tsx"),
    route("orders", "routes/orders.tsx"),
    // Telegram order alerts link to /orders/{id} (dupli1#158).
    route("orders/:id", "routes/orders.tsx", { id: "order-detail" }),
    route("coupons", "routes/coupons.tsx"),
    route("analytics", "routes/analytics.tsx"),
    route("telegram", "routes/telegram.tsx"),
    route("users", "routes/users.tsx"),
    route("users/new", "routes/users.new.tsx"),
    route("users/:id", "routes/users.$id.tsx"),
    route("settings", "routes/settings.tsx"),
  ]),
] satisfies RouteConfig;
